language: node_js
deploy:
  api_key:
    secure: bBMDbtd5+HngafcemSQS8hmokrssMrt8H+V2J6NIkR+yb6qHvpcSfftk2bnxvNFasfDV+2odMUtQd8ULWs7wA5U4bTdou3VGUKGnT8Slw+OepLhruZqwDfT2RIGzalpmnlgtAmOD2lBnpS3DthkDmFfO1/lJPFAY/T20OAk1ola0zqA6mHHib7s5W7rb5rmk93eFVRheCuYoLg1ta2FaEBJmN4eZZIMVCpBQhTfZ0vjRXtfrWwiK0Z5LbfZgukZTxRzMJ3tdjrejujvb1iUruTwYeY18Y+NNC2FCLiw2sCtaruwlL+Ip/ks2Snyd2BH+giOyDZ5oh/niEH+VR7alzbYNUyXVvLysS3BFAGmWKfHwtOmlz7Eg8PiAs9lat6zbeF5AwnZ0PDOwbmGhMebyPATWUUmMnBjCuicrUXk/bpiQqSdpGLnYph8Wzq2TNV4bs2C//oSfCNCp0G+E2EzA4nwvQAIg8jS7cmtLPSUxzvXIF6PPuZdhMMa79elFiAGeCj/Eh/FDw7ECFB15gSHqKqnLFUrDtDW4SZpv9pr/SHIydRR3ssNv+yK3T2Lqhst6zy2KNXU9Wm+Oeycdq8tyz3vKhzcGKPs/F11BwhdriDQRNIRMu70h0O7LvEVVlE80SqGr0O8/KTVxI+F2Sa2CE7NtRpoCAAWLlycbz6EMmyc=
  email: lotosbin@gmail.com
  provider: npm
